language: rust
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - name: "master doc to gh-pages"
      rust: nightly
      if: branch = master
      script:
        - cargo doc --no-deps
        - curl -O https://raw.githubusercontent.com/alexcrichton/rust-travis-deploy/master/travis-deploy.rs
        - rustc travis-deploy.rs
        - (cd target/doc && ../../travis-deploy)
script:
  - cargo build --verbose
  - cargo test --verbose
notifications:
  email:
    on_success: never
